### PR TITLE
Create dependabot.yml

### PR DESCRIPTION
**Pull request by jbygdell**

### CODE REVIEW

**Review by norling — DISMISSED** [review]
I haven't tested anything, but this looks reasonable.

**Review by dbampalikis — COMMENTED** [review]
Maybe we should have kostas in the list of reviewers too?

**Review by norling — APPROVED** [review]
I agree with dimi that it might be reasonable to have kostas as reviewer as well, looks good otherwise !

**Review by norling — APPROVED** [review]
Shouldn't kostas be a gomod reviewer as well? otherwise - looks great!

**Review by norling — APPROVED** [review]
...and all is well with the world.

**Pull request merged**
